import '@/styles/globals.css';
import type { AppProps } from 'next/app';
import { Montserrat, Lato } from 'next/font/google';

export const mont = Montserrat({
  variable: '--font-mont',
  subsets: ['latin'],
});
export const lato = Lato({
  variable: '--font-lato',
  subsets: ['latin'],
  weight: ['100', '300', '400', '700', '900'],
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function App({ Component, pageProps }: AppProps) {
  return (
    <main className={`${mont.variable} ${lato.variable}`}>
      <Component {...pageProps} />
    </main>
  );
}
